import Head from "next/head";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import { useCallback } from "react";

import Particles from "react-tsparticles";
import type { Container, Engine, RecursivePartial } from "tsparticles-engine";
import { loadFull } from "tsparticles";
import PARTICLES_CONFIG from "../public/particlesjs-config.json";

export default function Home() {
  const particlesInit = useCallback(async (engine: Engine) => {
    console.log(engine);

    // you can initialize the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine);
  }, []);

  const particlesLoaded = useCallback(
    async (container: Container | undefined) => {
      await console.log(container);
    },
    []
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>this is me.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Particles
        id="tsparticles"
        options={PARTICLES_CONFIG as RecursivePartial<any>}
        init={particlesInit}
        loaded={particlesLoaded}
      />

      <div className=" absolute flex flex-row justify-center items-center w-screen h-screen px-10">
        <motion.button
          className="w-24 h-24 bg-slate-600"
          whileHover={{ scale: 2 }}
          animate={{
            opacity: [1, 0.7, 0.5, 0.7, 1],
            rotate: [0, 270, 90, 0],
            borderRadius: ["20%", "75%", "20%"],
          }}
          transition={{
            repeat: Infinity,
            repeatDelay: 1,
          }}
        />
      </div>

      <main className={styles.main}></main>
    </div>
  );
}
